title: Sims4Hub
email: your-email@domain.com
description: Write an awesome description for your new site here. You can edit this search results) and in your feed.xml site description.
baseurl: ""
url: "https://sims4hub.ga"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: :compressed